services:
  telograf-simple:
    image: diffusion
    container_name: telograf_simple_container
    network_mode: host
    environment:
      - DISPLAY=${DISPLAY}
      - NVIDIA_VISIBLE_DEVICES=all
      - WANDB_API_KEY=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
      - REQUESTS_CA_BUNDLE=/etc/ssl/certs/ca-certificates.crt
      - SSL_CERT_FILE=/etc/ssl/certs/ca-certificates.crt
    volumes:
      - .:/app
      - ~/abb_root.cer:/usr/local/share/ca-certificates/abb_root.crt:ro
      - /tmp/.X11-unix:/tmp/.X11-unix
    command: bash -c "
      update-ca-certificates && 
      wandb login && 
      cd project/code && bash run_icml2025_test.sh"
    stdin_open: true
    tty: true
    runtime: nvidia

    # train_RL_with_BC
    # run_PF_controller
    # python -B plot_figures.py
    # bash run_icml2025_train.sh
    # pip install imageio tqdm einops pytorch_kinematics psutil torch_geometric cma pandas matplotlib && 
