# Test / eval config
flow: true
first_sat_init: true
skip_first_eval: true
clip_max: 50000
max_sol_clip: 2
type_ratios: [1, 3, 2, 4]
num_evals: 128
batch_size: 1
max_viz: 128
test_muls: 1024
val_eval_only: true
